- name: Install tools
  become: true
  ansible.builtin.apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 3600

- name: Create folders
  become_user: satoshi
  ansible.builtin.file:
    path: ~/downloads
    state: directory