
# see https://youtu.be/fx_mLXISrfM?list=PLCRbH-IWlcW2A_kpx2XwAMgT0rcZEZ2Cg&t=41
- name: Download Bitcoin Core
  become_user: satoshi
  ansible.builtin.get_url:
    url: '{{ bitcoin_core_download_url }}'
    dest: '~/downloads/{{ bitcoin_core_folder_name }}.tar.gz'
    checksum: 'sha256:{{ bitcoin_core_checksums_url }}'
    timeout: 30

# see https://youtu.be/fx_mLXISrfM?list=PLCRbH-IWlcW2A_kpx2XwAMgT0rcZEZ2Cg&t=279
- name: Unarchive Bitcoin Core
  become_user: satoshi
  ansible.builtin.unarchive:
    remote_src: yes
    src: ~/downloads/{{ bitcoin_core_folder_name }}.tar.gz
    dest: ~/downloads/

# see https://youtu.be/fx_mLXISrfM?list=PLCRbH-IWlcW2A_kpx2XwAMgT0rcZEZ2Cg&t=300
- name: Install Bitcoin Core
  become: true
  shell: 'install -m 0755 -o root -g root -t /usr/local/bin /home/{{ ansible_user }}/downloads/{{ bitcoin_core_folder_name }}/bin/*'

# see https://youtu.be/fx_mLXISrfM?list=PLCRbH-IWlcW2A_kpx2XwAMgT0rcZEZ2Cg&t=334
- name: Start Bitcoin Core Daemon
  become_user: satoshi
  shell: bitcoind -daemon

# see https://youtu.be/fx_mLXISrfM?list=PLCRbH-IWlcW2A_kpx2XwAMgT0rcZEZ2Cg&t=675
- name: Download rpcauth.py
  become_user: satoshi
  ansible.builtin.get_url:
    url: '{{ rpcauth_source_url }}'
    dest: '~/downloads/rpcauth.py'
    mode: a+x
    timeout: 30

# see https://youtu.be/fx_mLXISrfM?list=PLCRbH-IWlcW2A_kpx2XwAMgT0rcZEZ2Cg&t=586
- name: Create bitcoin.conf file
  become_user: satoshi
  ansible.builtin.template:
    src: bitcoin.conf
    dest: '~/.bitcoin/bitcoin.conf'

# see https://youtu.be/fx_mLXISrfM?list=PLCRbH-IWlcW2A_kpx2XwAMgT0rcZEZ2Cg&t=675
- name: Execute rpcauth.py
  become_user: satoshi
  shell: './rpcauth.py {{ bitcoin_core_username }} {{ bitcoin_core_password }}'
  args:
    chdir: '~/downloads'
  register: rpcauth_result

- set_fact:
    rpcauth_value: "{{ rpcauth_result.stdout_lines[1] }}"

- name: Insert rpcauth into bitcoin.conf
  become_user: satoshi
  ansible.builtin.lineinfile:
    path: '~/.bitcoin/bitcoin.conf'
    regexp: '^rpcauth=bitcoin:'
    line: '{{ rpcauth_value }}'
    insertafter: '^whitelist'

# see https://youtu.be/fx_mLXISrfM?list=PLCRbH-IWlcW2A_kpx2XwAMgT0rcZEZ2Cg&t=970
- name: Download bitcoind.service file
  become: true
  ansible.builtin.get_url:
    url: '{{ bitcoind_service_source_url }}'
    dest: '/etc/systemd/system/bitcoind.service'

# see https://youtu.be/fx_mLXISrfM?t=1030
- name: In bitcoind.service - Replace -daemonwait with -daemon
  become: true
  ansible.builtin.replace:
    path: /etc/systemd/system/bitcoind.service
    regexp: '-daemonwait'
    replace: '-daemon'

# see https://youtu.be/fx_mLXISrfM?t=1030
- name: In bitcoind.service - Replace bitcoind executable
  become: true
  ansible.builtin.replace:
    path: /etc/systemd/system/bitcoind.service
    regexp: '/usr/bin/bitcoind'
    replace: '/usr/local/bin/bitcoind'

# see https://youtu.be/fx_mLXISrfM?t=1030
- name: In bitcoind.service - Replace -conf
  become: true
  ansible.builtin.replace:
    path: /etc/systemd/system/bitcoind.service
    regexp: '/etc/bitcoin/bitcoin.conf'
    replace: '/home/{{ ansible_user }}/.bitcoin/bitcoin.conf'

# see https://youtu.be/fx_mLXISrfM?t=1030
- name: In bitcoind.service - Replace -datadir
  become: true
  ansible.builtin.replace:
    path: /etc/systemd/system/bitcoind.service
    regexp: '/var/lib/bitcoind'
    replace: '/home/{{ ansible_user }}/.bitcoin'

# see https://youtu.be/fx_mLXISrfM?t=1030
- name: In bitcoind.service - Comment out ExecStartPre
  become: true
  ansible.builtin.replace:
    path: /etc/systemd/system/bitcoind.service
    regexp: 'ExecStartPre'
    replace: '# ExecStartPre'

# see https://youtu.be/fx_mLXISrfM?t=1030
- name: In bitcoind.service - Change User
  become: true
  ansible.builtin.replace:
    path: /etc/systemd/system/bitcoind.service
    regexp: 'User=bitcoin'
    replace: 'User={{ ansible_user }}'

# see https://youtu.be/fx_mLXISrfM?t=1030
- name: In bitcoind.service - Change Group
  become: true
  ansible.builtin.replace:
    path: /etc/systemd/system/bitcoind.service
    regexp: 'Group=bitcoin'
    replace: 'Group={{ ansible_user }}'

# see https://youtu.be/fx_mLXISrfM?t=1030
- name: In bitcoind.service - Comment out ProtectHome
  become: true
  ansible.builtin.replace:
    path: /etc/systemd/system/bitcoind.service
    regexp: 'ProtectHome'
    replace: '# ProtectHome'

# see https://youtu.be/fx_mLXISrfM?t=1172
- name: Enable systemd service
  become: true
  ansible.builtin.systemd:
    state: started
    enabled: yes
    daemon_reload: yes
    name: bitcoind

